name: Build

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { os: linux, arch: 386 }
          - { os: linux, arch: amd64 }
          - { os: linux, arch: arm64 }
          - { os: windows, arch: 386 }
          - { os: windows, arch: amd64 }
          - { os: windows, arch: arm64 }
          - { os: darwin, arch: amd64 }
          - { os: darwin, arch: arm64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build (${{ matrix.os }}-${{ matrix.arch }})
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o ./bin/${{ matrix.os }}_${{ matrix.arch }}/

      - name: Move binaries
        run: |
          mkdir -p ./temp/${{ matrix.os }}_${{ matrix.arch }}
          mv ./bin/${{ matrix.os }}_${{ matrix.arch }}/* ./temp/${{ matrix.os }}_${{ matrix.arch }}/

      - name: Package files for linux/darwin
        if: ${{ matrix.os == 'linux' || matrix.os == 'darwin' }}
        run: |
          mkdir -p ./release
          cd ./temp/${{ matrix.os }}_${{ matrix.arch }}
          tar -czf ${{ github.workspace }}/release/nomad-ls_${{ matrix.os }}_${{ matrix.arch }}.tar.gz *

      - name: Package files for windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          mkdir -p ./release
          cd ./temp/${{ matrix.os }}_${{ matrix.arch }}
          zip -r ${{ github.workspace }}/release/nomad-ls_${{ matrix.os }}_${{ matrix.arch }}.zip *

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*
          draft: true
